name: Continuos Integration
on:
  push:
    branches:
        main
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3
    
    - run: npm ci

    - name: Copy files with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        REMOTE_HOST: "ec2-54-233-39-138.sa-east-1.compute.amazonaws.com"
        REMOTE_USER: "ec2_user"
        TARGET: "/home/ec2-user"
        EXCLUDE: "/dist/, /node_modules/, **.env, rebuild_app.sh, watcher.sh"